version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
  node: circleci/node@2.0.3
docker_default: &default
  docker:
    - image: "cimg/base:stable"
jobs:
  run-tests-latest:
    <<: *default
    steps:
      - node/install:
          install-yarn: true
          node-version: latest
      - run: node --version
      - node/install-packages:
          pkg-manager: yarn
          cache-key: yarn.lock
      - run:
          name: Run Linter
          command: yarn lint
      - run:
          name: Run tests
          command: yarn test
      - codecov/upload:
          file: coverage/*.json
  run-tests-legacy:
    <<: *default
    steps:
      - node/install:
          node-version: 6.15.1-browsers-legacy
      - run: node --version
      - node/install-packages
      - run:
          name: Run Linter
          command: yarn lint
      - run:
          name: Run tests
          command: yarn test
      - codecov/upload:
          file: coverage/*.json
workflows:
  run-tests:
    jobs:
      - checkout
      - run-tests-latest
      - run-tests-legacy
