version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
  node: circleci/node@2.0.3
jobs:
  run-tests:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: latest
      - run: node --version
      - node/install-packages:
          pkg-manager: yarn
          cache-key: yarn.lock
      - run:
          name: Run Linter
          command: yarn lint
      - run:
          name: Run tests
          command: yarn test
      - codecov/upload:
          file: coverage/*.json
workflows:
  workflow:
    jobs:
      - run-tests
