version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
  node: circleci/node@2.0.3
jobs:
  build-test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - run: node --version
      - node/install-packages
      - run:
          name: Run Linter
          command: yarn lint
      - run:
          name: Run tests
          command: yarn test
      - codecov/upload:
          file: coverage/*.json
workflows:
  matrix-tests:
    jobs:
      - node/test:
          version: latest
      - node/test:
          version: 6.15.1-browsers-legacy
